/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IUniswapSwapProxy,
  IUniswapSwapProxyInterface,
} from "../IUniswapSwapProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20Extension",
        name: "_fromToken",
        type: "address",
      },
      {
        internalType: "contract IERC20Extension",
        name: "_toToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_gasRefund",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_slippage",
        type: "uint256",
      },
    ],
    name: "proxySwapWithFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IUniswapSwapProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapSwapProxyInterface {
    return new utils.Interface(_abi) as IUniswapSwapProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapSwapProxy {
    return new Contract(address, _abi, signerOrProvider) as IUniswapSwapProxy;
  }
}
