/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IForwardingSwapProxyInterface extends ethers.utils.Interface {
  functions: {
    "proxySwapWithFee(address,address,(address,uint256,uint256,bytes),uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "proxySwapWithFee",
    values: [
      string,
      string,
      {
        to: string;
        amount: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      },
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "proxySwapWithFee",
    data: BytesLike
  ): Result;

  events: {};
}

export class IForwardingSwapProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IForwardingSwapProxyInterface;

  functions: {
    proxySwapWithFee(
      _fromToken: string,
      _toToken: string,
      _swapParams: {
        to: string;
        amount: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      },
      _gasRefund: BigNumberish,
      _minimumReturnAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  proxySwapWithFee(
    _fromToken: string,
    _toToken: string,
    _swapParams: {
      to: string;
      amount: BigNumberish;
      value: BigNumberish;
      data: BytesLike;
    },
    _gasRefund: BigNumberish,
    _minimumReturnAmount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    proxySwapWithFee(
      _fromToken: string,
      _toToken: string,
      _swapParams: {
        to: string;
        amount: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      },
      _gasRefund: BigNumberish,
      _minimumReturnAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    proxySwapWithFee(
      _fromToken: string,
      _toToken: string,
      _swapParams: {
        to: string;
        amount: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      },
      _gasRefund: BigNumberish,
      _minimumReturnAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    proxySwapWithFee(
      _fromToken: string,
      _toToken: string,
      _swapParams: {
        to: string;
        amount: BigNumberish;
        value: BigNumberish;
        data: BytesLike;
      },
      _gasRefund: BigNumberish,
      _minimumReturnAmount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
